/**
 * B-5 — Per-route Open Graph stills (1200×630) under /images/og/.
 * Generated by scripts/render-route-og.mjs from scripts/og/route-og-template.html.
 */
export const ROUTE_OG_IMAGES: Record<string, string> = {
  "/": "/images/og/home.png",
  "/about": "/images/og/about.png",
  "/about/mission-values": "/images/og/about.png",
  "/about/team": "/images/og/about-team.png",
  "/store": "/images/og/store.png",
  "/resources/blog": "/images/og/blog.png",
  "/portal/login": "/images/og/portal-login.png",
  "/portal/dashboard": "/images/og/portal-dashboard.png",
};

const SITE_URL = "https://digeratiexperts.com";

/** Absolute og:image URL when a branded route still exists; otherwise undefined. */
export function absoluteOgImageForPath(pathname: string): string | undefined {
  const normalized = pathname.length > 1 && pathname.endsWith("/") ? pathname.slice(0, -1) : pathname;
  const rel = ROUTE_OG_IMAGES[normalized] ?? ROUTE_OG_IMAGES[pathname];
  return rel ? `${SITE_URL}${rel}` : undefined;
}
