/**
 * Prefix/exact allowlist for production SPA catch-all status codes.
 * Known client routes get 200 + index.html; everything else gets 404 + index.html
 * so crawlers see a real not-found without breaking deep links.
 */
const EXACT = new Set([
  "/",
  "/experience",
  "/versions",
  "/version-0",
  "/version-1",
  "/version-2",
  "/version-3",
  "/version-4",
  "/version-5",
  "/version-6",
  "/version-7",
  "/version-8",
  "/solutions",
  "/solutions/managed-it-support",
  "/solutions/managed-workplace",
  "/solutions/backup-disaster-recovery",
  "/solutions/ProActive-Ecosystem-Packages",
  "/solutions/proactive-ecosystem-packages",
  "/solutions/proactive-ecosystem",
  "/solutions/proactive-it-ecosystem",
  "/solutions/proactive-office-ecosystem",
  "/solutions/proactive-business-ecosystem",
  "/solutions/proactive-enterprise-ecosystem",
  "/solutions/standalone-services",
  "/solutions/co-managed-it",
  "/solutions/request",
  "/solutions/endpoint-management",
  "/solutions/identity-management",
  "/solutions/email-security",
  // Data-driven solution pages (client/src/pages/routes/servicePages.tsx keys
  // routed by App.tsx). They rendered while answering HTTP 404 to crawlers and
  // link checkers until 2026-09-30; the test below keeps the two lists in step.
  "/solutions/cloud-backup",
  "/solutions/security-awareness",
  "/solutions/threat-detection",
  "/solutions/security-operations",
  "/solutions/vcio-strategy",
  "/solutions/data-encryption",
  "/solutions/compliance-reports",
  "/solutions/unified-security",
  "/solutions/professional-services",
  "/solutions/system-status",
  "/store",
  "/store/checkout",
  "/store/solution",
  "/services/ucaas",
  "/industries",
  "/industries/healthcare",
  "/industries/accounting-finance",
  "/industries/law-firms",
  "/industries/real-estate",
  "/industries/nonprofits",
  "/industries/animal-hospitals",
  "/the-box",
  "/resources",
  "/resources/case-studies",
  "/resources/blog",
  "/resources/cyber-facts",
  "/resources/ebook/defending-digital-realm",
  "/resources/security-updates",
  "/resources/videos",
  "/resources/security-checklist",
  "/resources/datasheets",
  "/resources/downtime-calculator",
  "/about/mission",
  "/about/mission-values",
  "/about/team",
  "/about/compliance",
  "/about/support",
  "/about/insurance",
  "/about/compliance-certifications",
  "/about/client-bill-of-rights",
  "/about/guarantee",
  "/about/21-questions",
  "/about/press",
  "/support/ticket-confirmation",
  "/support/submit-ticket",
  "/support/knowledge-base",
  "/support/remote-support",
  "/support/pay-invoice",
  // Data-driven support and industry pages (supportPageData / industryPageData in
  // client/src/pages/routes/servicePages.tsx, routed by App.tsx).
  "/support/system-status",
  "/industries/professional-services",
  "/privacy",
  "/terms",
  "/legal/privacy-policy",
  "/legal/terms-of-use",
  "/legal/msa",
  "/legal/sla",
  "/legal/aup",
  "/legal/dpa",
  "/legal/sample-sow",
  "/trust",
  "/trust/trust-center",
  "/trust/vulnerability-disclosure",
  "/trust/accessibility",
  "/locations/chandler-az",
  "/locations/phoenix-az",
  "/locations/mesa-az",
  "/locations/gilbert-az",
  "/locations/tempe-az",
  "/locations/scottsdale-az",
  "/login",
  "/signup",
  "/portal",
  "/quote-wizard",
  "/quote-confirmation",
  "/thank-you-success-page",
  "/proactive-ecosystem-pricing",
  "/pricing",
  "/ecosystem-pricing",
  "/de-ecosystem-matrix-offical",
  "/official-network-planner",
  "/book",
  "/assessment",
  "/contact",
  "/case-studies",
  // Marketing pages that client/src/pages/MarketingRouteFallback.tsx renders:
  // campaign landings, executive briefs and resource asset pages. Until
  // 2026-10-01 they rendered while answering HTTP 404 (27 of the 113 sitemap
  // URLs). Exact paths, not prefixes, so an unknown slug still answers 404; the
  // tests keep this list in step with the sitemap and the client data.
  "/go",
  "/go/cyber-risk-assessment",
  "/go/managed-it",
  "/go/ransomware-readiness",
  "/go/co-managed-it",
  "/go/healthcare-it",
  "/go/cyber-insurance",
  "/go/email-security",
  "/go/proactive-business",
  "/resources/briefs",
  "/resources/briefs/cyber-risk-operating-brief",
  "/resources/briefs/ransomware-readiness-brief",
  "/resources/briefs/cyber-insurance-brief",
  "/resources/briefs/proactive-operating-brief",
  "/resources/datasheets/proactive-ecosystem-overview",
  "/resources/datasheets/managed-workplace-overview",
  "/resources/datasheets/proactive-it-ecosystem-datasheet",
  "/resources/datasheets/proactive-office-ecosystem-datasheet",
  "/resources/datasheets/proactive-business-ecosystem-datasheet",
  "/resources/datasheets/proactive-enterprise-ecosystem-datasheet",
  "/resources/datasheets/co-managed-it-datasheet",
  "/resources/datasheets/ucaas-voice-meetings-datasheet",
  "/resources/reports/cyber-risk-assessment-sample",
  "/resources/reports/compliance-risk-reports-overview",
  "/resources/reports/sample-quarterly-business-review",
  "/resources/checklists/security-readiness-checklist",
  "/resources/checklists/backup-bcdr-checklist",
]);

const PREFIXES = [
  "/store/solutions/",
  "/store/solution/submitted/",
  "/resources/case-studies/",
  "/resources/blog/",
  "/portal/",
  "/internal/warehouse",
  "/assets/",
  "/images/",
  "/brand/",
  "/attached_assets/",
];

export function normalizeSpaPath(pathname: string): string {
  const raw = (pathname.split("?")[0] || pathname).toLowerCase();
  if (raw.length <= 1) return raw || "/";
  return raw.replace(/\/+$/, "") || "/";
}

export function isKnownSpaPath(pathname: string): boolean {
  const path = normalizeSpaPath(pathname);
  if (EXACT.has(path)) return true;
  return PREFIXES.some((prefix) => path === prefix.replace(/\/+$/, "") || path.startsWith(prefix));
}
