/**
 * Prefix/exact allowlist for production SPA catch-all status codes.
 * Known client routes get 200 + index.html; everything else gets 404 + index.html
 * so crawlers see a real not-found without breaking deep links.
 */
const EXACT = new Set([
  "/",
  "/experience",
  "/versions",
  "/version-1",
  "/version-2",
  "/version-3",
  "/solutions",
  "/solutions/managed-it-support",
  "/solutions/managed-workplace",
  "/solutions/backup-disaster-recovery",
  "/solutions/ProActive-Ecosystem-Packages",
  "/solutions/proactive-ecosystem-packages",
  "/solutions/proactive-ecosystem",
  "/solutions/proactive-it-ecosystem",
  "/solutions/proactive-office-ecosystem",
  "/solutions/proactive-business-ecosystem",
  "/solutions/proactive-enterprise-ecosystem",
  "/solutions/standalone-services",
  "/solutions/co-managed-it",
  "/solutions/business-needs",
  "/solutions/request",
  "/solutions/endpoint-management",
  "/solutions/identity-management",
  "/solutions/email-security",
  "/store",
  "/store/checkout",
  "/store/solution",
  "/services/ucaas",
  "/industries",
  "/industries/healthcare",
  "/industries/accounting-finance",
  "/industries/law-firms",
  "/industries/real-estate",
  "/industries/nonprofits",
  "/industries/animal-hospitals",
  "/resources",
  "/resources/case-studies",
  "/resources/blog",
  "/resources/cyber-facts",
  "/resources/ebook/defending-digital-realm",
  "/resources/security-updates",
  "/resources/videos",
  "/resources/security-checklist",
  "/resources/datasheets",
  "/resources/downtime-calculator",
  "/about/mission",
  "/about/mission-values",
  "/about/team",
  "/about/compliance",
  "/about/support",
  "/about/insurance",
  "/about/compliance-certifications",
  "/about/client-bill-of-rights",
  "/about/guarantee",
  "/about/21-questions",
  "/about/press",
  "/support/ticket-confirmation",
  "/support/submit-ticket",
  "/support/knowledge-base",
  "/support/remote-support",
  "/support/pay-invoice",
  "/privacy",
  "/terms",
  "/legal/privacy-policy",
  "/legal/terms-of-use",
  "/legal/msa",
  "/legal/sla",
  "/legal/aup",
  "/legal/dpa",
  "/legal/sample-sow",
  "/trust",
  "/trust/trust-center",
  "/trust/vulnerability-disclosure",
  "/trust/accessibility",
  "/locations/chandler-az",
  "/locations/phoenix-az",
  "/locations/mesa-az",
  "/locations/gilbert-az",
  "/locations/tempe-az",
  "/locations/scottsdale-az",
  "/login",
  "/signup",
  "/portal",
  "/quote-wizard",
  "/quote-confirmation",
  "/thank-you-success-page",
  "/proactive-ecosystem-pricing",
  "/pricing",
  "/ecosystem-pricing",
  "/de-ecosystem-matrix-offical",
  "/official-network-planner",
  "/book",
  "/assessment",
  "/contact",
  "/case-studies",
]);

const PREFIXES = [
  "/solutions/business-needs/",
  "/store/solutions/",
  "/resources/case-studies/",
  "/resources/blog/",
  "/portal/",
  "/internal/warehouse",
  "/assets/",
  "/images/",
  "/brand/",
  "/attached_assets/",
];

export function normalizeSpaPath(pathname: string): string {
  const raw = pathname.split("?")[0] || pathname;
  if (raw.length <= 1) return raw || "/";
  return raw.replace(/\/+$/, "") || "/";
}

export function isKnownSpaPath(pathname: string): boolean {
  const path = normalizeSpaPath(pathname);
  if (EXACT.has(path)) return true;
  return PREFIXES.some((prefix) => path === prefix.replace(/\/+$/, "") || path.startsWith(prefix));
}
