<#
.SYNOPSIS
    Generates windows\playbooks\: one ready-to-run DE Tech Tool script per ProActive Ecosystem tier, per variant
    (GCC High, Co-Managed) and per standalone solution family, from catalog\bundles.json, so the scripts never
    drift from the catalog.

.DESCRIPTION
    Each playbook runs the console headless with its bundle or solution preset. Audit by default (changes
    nothing); -Apply to provision; -Mode auto picks the mode from discovery. RMM secure variables named
    DE_SECRET_<NAME> supply runtime secrets; -PromptSecrets asks for missing ones interactively.
    Run this after editing either catalog; a Pester test fails if a playbook is missing or stale.
#>
[CmdletBinding()]
param([string]$WindowsRoot, [string]$OutDir)
Set-StrictMode -Version 1.0
$ErrorActionPreference = 'Stop'
$here = $(if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path })   # $PSScriptRoot can be empty in param defaults on Windows PowerShell 5.1
if (-not $WindowsRoot) { $WindowsRoot = Split-Path -Parent $here }
$catalog = Join-Path (Join-Path $WindowsRoot 'console') 'catalog'
$outDir = $(if ($OutDir) { $OutDir } else { Join-Path $WindowsRoot 'playbooks' })
New-Item -ItemType Directory -Path $outDir -Force | Out-Null
$cat = Get-Content -LiteralPath (Join-Path $catalog 'bundles.json') -Raw | ConvertFrom-Json
$bundles = @(foreach ($t in $cat.proactive.PSObject.Properties) { [pscustomobject]@{ id = $t.Value.bundleId; name = $t.Value.label } }) + @(foreach ($v in @($cat.variants)) { [pscustomobject]@{ id = $v.id; name = $v.label } })
$solutions = @(foreach ($s in $cat.standaloneSolutions.PSObject.Properties) { [pscustomobject]@{ id = $s.Value.id; name = $s.Value.label } })

function ConvertTo-FileName { param([string]$Name) return (($Name -replace '[()]', '' -replace '&', 'and' -replace '[^A-Za-z0-9]+', '-').Trim('-')) }

$template = @'
<#
.SYNOPSIS  {TITLE}
.DESCRIPTION
    Preconfigured DE Tech Tool playbook ({KIND}: {ID}). Generated by packaging\New-DEPlaybooks.ps1
    from the console catalog; do not edit by hand. Audit by default (changes nothing). Exit codes: 0 ready,
    1 not ready, 2 blocked.
.EXAMPLE
    .\{FILE} -Client alamo                    # audit against the {NAME} plan
    .\{FILE} -Client alamo -Mode auto -Apply  # let discovery pick the mode, then provision
#>
[CmdletBinding(SupportsShouldProcess = $true)]
param(
    [Parameter(Mandatory = $true)][string]$Client,
    [ValidateSet('auto', 'audit', 'new', 'takeover', 'replacement', 'repair', 'co-managed', 'deprovision', 'dropship')][string]$Mode = 'audit',
    [switch]$Apply,
    [string[]]$AddOn = @(),
    [string]$Order,
    [switch]$PromptSecrets,
    [string]$Technician = 'jrpetro'
)
$console = Join-Path (Join-Path (Split-Path -Parent $PSScriptRoot) 'console') 'DETechConsole.ps1'
if (-not (Test-Path -LiteralPath $console)) { Write-Error "DE Tech Tool not found at $console (keep this script in windows\playbooks)"; exit 2 }
$argList = @('-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $console, '-Headless', '-Client', $Client, '-Mode', $Mode, '-Technician', $Technician, {PRESET})
if ($Apply) { $argList += '-Apply' }
if ($Order) { $argList += @('-Order', $Order) }
if ($PromptSecrets) { $argList += '-PromptSecrets' }
if (@($AddOn | Where-Object { $_ }).Count) { $argList += @('-AddOn', (($AddOn | Where-Object { $_ }) -join ',')) }
if ($WhatIfPreference) { $argList += '-WhatIf' }
# a child process keeps the tool's exit code (0 ready, 1 not ready, 2 blocked) and its own module scope;
# a host that is not powershell/pwsh (ISE, an RMM agent's own exe) would lose the exit code, so use powershell.exe then
$shell = (Get-Process -Id $PID).Path; if ([IO.Path]::GetFileNameWithoutExtension($shell) -notin @('powershell', 'pwsh')) { $shell = 'powershell.exe' }
& $shell @argList
if ($null -eq $LASTEXITCODE) { exit 1 }
exit $LASTEXITCODE
'@

$written = @()
foreach ($b in $bundles) {
    $file = "$(ConvertTo-FileName $b.name).ps1"
    $body = $template.Replace('{TITLE}', "$($b.name): audit or provision a device for this ProActive Ecosystem plan").Replace('{KIND}', 'bundle').Replace('{ID}', $b.id).Replace('{NAME}', $b.name).Replace('{FILE}', $file).Replace('{PRESET}', "'-Bundle', '$($b.id)'")
    [IO.File]::WriteAllText((Join-Path $outDir $file), $body, (New-Object Text.UTF8Encoding $true)); $written += $file
}
foreach ($s in $solutions) {
    $file = "Standalone-$(ConvertTo-FileName $s.name).ps1"
    $body = $template.Replace('{TITLE}', "Standalone $($s.name): the preconfigured DE solution without managed services").Replace('{KIND}', 'standalone solution').Replace('{ID}', $s.id).Replace('{NAME}', "standalone $($s.name)").Replace('{FILE}', $file).Replace('{PRESET}', "'-Solution', '$($s.id)'")
    [IO.File]::WriteAllText((Join-Path $outDir $file), $body, (New-Object Text.UTF8Encoding $true)); $written += $file
}
# stale playbooks for bundles or solutions that left the catalog are removed
foreach ($f in Get-ChildItem -LiteralPath $outDir -Filter '*.ps1') { if ($written -notcontains $f.Name) { Remove-Item -LiteralPath $f.FullName -Force } }
Write-Host ("Wrote {0} playbooks to {1}" -f $written.Count, $outDir)
$written
