import { chromium } from "playwright-core";
const W = +(process.env.W || 1440), H = +(process.env.H || 900);
const out = new URL(`./${W}/`, import.meta.url).pathname;
import { mkdirSync } from "fs"; mkdirSync(out, { recursive: true });
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const p = await b.newPage({ viewport: { width: W, height: H }, reducedMotion: process.env.REDUCED ? "reduce" : "no-preference" });
const errs = []; p.on("pageerror", e => errs.push(e.message)); p.on("console", m => m.type() === "error" && errs.push(m.text()));
await p.addInitScript((k) => { try { if (k) localStorage.setItem("sg-kept-v1", k); } catch {} }, process.env.KEPT ?? JSON.stringify(["it-person-left","new-hires-fast","hybrid-byod","insurance-questionnaire","internal-it-stretched"]));
await p.goto("http://localhost:4510/", { waitUntil: "networkidle" });
await p.addStyleTag({ content: "html{scroll-behavior:auto !important}" }); await p.waitForTimeout(600);
const at = async (name, fn) => { const y = await p.evaluate(fn); await p.evaluate(y => window.scrollTo(0, y), y); await p.waitForTimeout(900); await p.screenshot({ path: out + name + ".png" }); };
const secAt = (sel, frac) => `(() => { const s = document.querySelector('${sel}'); const t = s.getBoundingClientRect().top + scrollY; return t + (s.offsetHeight - innerHeight) * ${frac}; })()`;
await at("00-top", "0");
await at("01-room1-mid", secAt("#room-now", 0.6));
await at("02-between", secAt(".between", 0.35));
await at("03-room2-mid", secAt("#room-change", 0.5));
await at("04-wall3", secAt(".wall3", 0));
await at("05-room3", secAt("#room-prove", 0.6));
await at("06-silence", secAt(".silence", 0.5));
for (const f of [0.1, 0.25, 0.42, 0.5, 0.62, 0.85]) await at("07-asm-" + f, secAt("#assembly", f));
await at("08-how", secAt(".how", 0.3));
await at("09-close", secAt("#close", 1));
const ov = await p.evaluate(() => document.documentElement.scrollWidth - innerWidth);
const rails = await p.evaluate(() => [...document.querySelectorAll("[data-sc-pan]")].map(r => r.scrollWidth - innerWidth));
console.log("overflow", ov, "rail overflow", rails.join(","), "errors", errs.length, errs.slice(0, 3).join(" | "));
await b.close();
