<#
.SYNOPSIS  ProActive IT: audit or provision a device for this ProActive Ecosystem plan
.DESCRIPTION
    Preconfigured DE Tech Tool playbook (bundle: proactive-it). Generated by packaging\New-DEPlaybooks.ps1
    from the console catalog; do not edit by hand. Audit by default (changes nothing). Exit codes: 0 ready,
    1 not ready, 2 blocked.
.EXAMPLE
    .\ProActive-IT.ps1 -Client alamo                    # audit against the ProActive IT plan
    .\ProActive-IT.ps1 -Client alamo -Mode auto -Apply  # let discovery pick the mode, then provision
#>
[CmdletBinding(SupportsShouldProcess = $true)]
param(
    [Parameter(Mandatory = $true)][string]$Client,
    [ValidateSet('auto', 'audit', 'new', 'takeover', 'replacement', 'repair', 'co-managed', 'deprovision', 'dropship')][string]$Mode = 'audit',
    [switch]$Apply,
    [string[]]$AddOn = @(),
    [string]$Order,
    [switch]$PromptSecrets,
    [string]$Technician = 'jrpetro'
)
$console = Join-Path (Join-Path (Split-Path -Parent $PSScriptRoot) 'console') 'DETechConsole.ps1'
if (-not (Test-Path -LiteralPath $console)) { Write-Error "DE Tech Tool not found at $console (keep this script in windows\playbooks)"; exit 2 }
$argList = @('-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $console, '-Headless', '-Client', $Client, '-Mode', $Mode, '-Technician', $Technician, '-Bundle', 'proactive-it')
if ($Apply) { $argList += '-Apply' }
if ($Order) { $argList += @('-Order', $Order) }
if ($PromptSecrets) { $argList += '-PromptSecrets' }
if (@($AddOn | Where-Object { $_ }).Count) { $argList += @('-AddOn', (($AddOn | Where-Object { $_ }) -join ',')) }
if ($WhatIfPreference) { $argList += '-WhatIf' }
# a child process keeps the tool's exit code (0 ready, 1 not ready, 2 blocked) and its own module scope
& (Get-Process -Id $PID).Path @argList
exit $LASTEXITCODE