<#
.SYNOPSIS  Standalone Identity & Access: the preconfigured DE solution without managed services
.DESCRIPTION
    Preconfigured DE Tech Tool playbook (standalone solution: identity_access). Generated by packaging\New-DEPlaybooks.ps1
    from the console catalog; do not edit by hand. Audit by default (changes nothing). Exit codes: 0 ready,
    1 not ready, 2 blocked.
.EXAMPLE
    .\Standalone-Identity-and-Access.ps1 -Client alamo                    # audit against the standalone Identity & Access plan
    .\Standalone-Identity-and-Access.ps1 -Client alamo -Mode auto -Apply  # let discovery pick the mode, then provision
#>
[CmdletBinding(SupportsShouldProcess = $true)]
param(
    [Parameter(Mandatory = $true)][string]$Client,
    [ValidateSet('auto', 'audit', 'new', 'takeover', 'replacement', 'repair', 'co-managed', 'deprovision', 'dropship')][string]$Mode = 'audit',
    [switch]$Apply,
    [string[]]$AddOn = @(),
    [string]$Order,
    [switch]$PromptSecrets,
    [string]$Technician   # asked once per machine and remembered when not given
)
$console = Join-Path (Join-Path (Split-Path -Parent $PSScriptRoot) 'console') 'DETechConsole.ps1'
if (-not (Test-Path -LiteralPath $console)) { Write-Error "DE Tech Tool not found at $console (keep this script in windows\playbooks)"; exit 2 }
$argList = @('-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $console, '-Headless', '-Client', $Client, '-Mode', $Mode, '-Solution', 'identity_access')
if ($Technician) { $argList += @('-Technician', $Technician) }
if ($Apply) { $argList += '-Apply' }
if ($Order) { $argList += @('-Order', $Order) }
if ($PromptSecrets) { $argList += '-PromptSecrets' }
if (@($AddOn | Where-Object { $_ }).Count) { $argList += @('-AddOn', (($AddOn | Where-Object { $_ }) -join ',')) }
if ($WhatIfPreference) { $argList += '-WhatIf' }
# a child process keeps the tool's exit code (0 ready, 1 not ready, 2 blocked) and its own module scope;
# a host that is not powershell/pwsh (ISE, an RMM agent's own exe) would lose the exit code, so use powershell.exe then
$shell = (Get-Process -Id $PID).Path; if ([IO.Path]::GetFileNameWithoutExtension($shell) -notin @('powershell', 'pwsh')) { $shell = 'powershell.exe' }
& $shell @argList
if ($null -eq $LASTEXITCODE) { exit 1 }
exit $LASTEXITCODE